name: Build and Deploy APK
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/BN-$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER.apk

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/BN-$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER.apk
